apiVersion: apps/v1
kind: Deployment
metadata:
  name: steadtlerhr
  labels:
    app: steadtlerhr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steadtlerhr
  template:
    metadata:
      labels:
        app: steadtlerhr
    spec:
      containers:
        - name: steadtlerhr
          image: shoebimtiaz/steadtlerhr:latest
          ports:
            - containerPort: 8080 
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development" 
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secrets
                  key: DB_Name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secrets
                  key: DB_User
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secrets
                  key: SA_PASSWORD
            - name: ConnectionStrings__SteadtlerHRDB
              value: "Server=sqlserver;Database=$(DB_NAME);User Id=$(DB_USER);Password=$(DB_PASSWORD);"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"  
