apiVersion: v1
kind: Service
metadata:
  name: steadtlerhr
  labels:
    app: steadtlerhr
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30001
  selector:
    app: steadtlerhr  